'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site_Mobile
    
    '''<summary>
    '''TransactionsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionsMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ReportMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ReportMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ItemMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ItemMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''VehiclestMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehiclestMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PersonnelMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PersonnelMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DepartmentsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepartmentsMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CompaniesMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompaniesMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ProductsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProductsMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''FluidSecureMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FluidSecureMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''FluidSecureHubMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FluidSecureHubMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TankChartsMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TankChartsMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TanksMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TanksMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DayLightSavingId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DayLightSavingId As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Reconciliation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Reconciliation As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Import control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Import As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Export control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Export As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CustomizedExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomizedExport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TransactionExportSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionExportSetting As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''StandardExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StandardExport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Export_WINCC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Export_WINCC As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''OtherMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OtherMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ShipmentMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipmentMenu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''UploadedFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadedFirmware As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''UploadedFSVMFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadedFSVMFirmware As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''UploadedFSNPFirmware control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UploadedFSNPFirmware As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CompanyHostingReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompanyHostingReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ShipmentReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShipmentReport As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CustomerWiseTransactionDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerWiseTransactionDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ResetTermsPrivacyPolicys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResetTermsPrivacyPolicys As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LogAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LogAction As Global.System.Web.UI.WebControls.LoginStatus
    
    '''<summary>
    '''lblMasterCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMasterCompanyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMasterCompanyName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdfHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfHide As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
