'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Resource
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Fuel_Secure.Resource", GetType(Resource).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active.
        '''</summary>
        Public Shared ReadOnly Property Active() As String
            Get
                Return ResourceManager.GetString("Active", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add new Personnel.
        '''</summary>
        Public Shared ReadOnly Property AddNewPersonnel() As String
            Get
                Return ResourceManager.GetString("AddNewPersonnel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you also want to activate all devices associated with this account?.
        '''</summary>
        Public Shared ReadOnly Property CheckActiveValue() As String
            Get
                Return ResourceManager.GetString("CheckActiveValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you also want to deactivate all devices associated with this account?.
        '''</summary>
        Public Shared ReadOnly Property CheckInActiveValue() As String
            Get
                Return ResourceManager.GetString("CheckInActiveValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company.
        '''</summary>
        Public Shared ReadOnly Property Company() As String
            Get
                Return ResourceManager.GetString("Company", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Public Shared ReadOnly Property Delete() As String
            Get
                Return ResourceManager.GetString("Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Department Name.
        '''</summary>
        Public Shared ReadOnly Property DepartmentName() As String
            Get
                Return ResourceManager.GetString("DepartmentName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Department Number.
        '''</summary>
        Public Shared ReadOnly Property DepartmentNumber() As String
            Get
                Return ResourceManager.GetString("DepartmentNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Public Shared ReadOnly Property Edit() As String
            Get
                Return ResourceManager.GetString("Edit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email.
        '''</summary>
        Public Shared ReadOnly Property Email() As String
            Get
                Return ResourceManager.GetString("Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error occurred while getting search column, please try again later..
        '''</summary>
        Public Shared ReadOnly Property ErrorMsg1() As String
            Get
                Return ResourceManager.GetString("ErrorMsg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error occurred while getting department, please try again later..
        '''</summary>
        Public Shared ReadOnly Property ErrorMsg2() As String
            Get
                Return ResourceManager.GetString("ErrorMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error occurred while getting customer, please try again later..
        '''</summary>
        Public Shared ReadOnly Property ErrorMsg3() As String
            Get
                Return ResourceManager.GetString("ErrorMsg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error occurred while getting access levels, please try again later..
        '''</summary>
        Public Shared ReadOnly Property ErrorMsg4() As String
            Get
                Return ResourceManager.GetString("ErrorMsg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error occurred while getting data, please try again later..
        '''</summary>
        Public Shared ReadOnly Property ErrorMsg5() As String
            Get
                Return ResourceManager.GetString("ErrorMsg5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FluidSecure.
        '''</summary>
        Public Shared ReadOnly Property FluidSecure() As String
            Get
                Return ResourceManager.GetString("FluidSecure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid HUB name. Please re-enter the HUB name or contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg1() As String
            Get
                Return ResourceManager.GetString("HandlerMsg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid company name. Please re-enter the company name or contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg10() As String
            Get
                Return ResourceManager.GetString("HandlerMsg10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unauthorized Wi-Fi selected. Please choose authorized FluidSecure Wi-Fi to proceed..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg11() As String
            Get
                Return ResourceManager.GetString("HandlerMsg11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your Location is not near an authorized Fuel Site. Please contact your Administrator for more information..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg12() As String
            Get
                Return ResourceManager.GetString("HandlerMsg12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Site not assigned. Please contact your Administrator for more information..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg13() As String
            Get
                Return ResourceManager.GetString("HandlerMsg13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMEI not exists.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg14() As String
            Get
                Return ResourceManager.GetString("HandlerMsg14", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some error has occurred, please try again after some time..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg15() As String
            Get
                Return ResourceManager.GetString("HandlerMsg15", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inactive vehicle, please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg16() As String
            Get
                Return ResourceManager.GetString("HandlerMsg16", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Department number is not valid, please try again.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg17() As String
            Get
                Return ResourceManager.GetString("HandlerMsg17", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Person PIN is invalid, please try again.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg18() As String
            Get
                Return ResourceManager.GetString("HandlerMsg18", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No data found for company,please try again.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg19() As String
            Get
                Return ResourceManager.GetString("HandlerMsg19", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not registered, Other Phone numbers are registered to same HUB..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg2() As String
            Get
                Return ResourceManager.GetString("HandlerMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your administrator has Not granted you the permission to fuel this vehicle. Please contact your administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg20() As String
            Get
                Return ResourceManager.GetString("HandlerMsg20", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your administrator has Not granted you the permission to fuel at this time of day. Please contact your administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg21() As String
            Get
                Return ResourceManager.GetString("HandlerMsg21", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your administrator has Not granted Hose the permission to fuel at this time of day. Please contact your administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg22() As String
            Get
                Return ResourceManager.GetString("HandlerMsg22", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your administrator has not given you the permission to fuel on this day. Please contact your administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg23() As String
            Get
                Return ResourceManager.GetString("HandlerMsg23", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This Vehicle is not permitted to fuel for this Hose, please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg24() As String
            Get
                Return ResourceManager.GetString("HandlerMsg24", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid vehicle number. Try again or contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg25() As String
            Get
                Return ResourceManager.GetString("HandlerMsg25", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your administrator has not granted you the permission to fuel at this location. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg26() As String
            Get
                Return ResourceManager.GetString("HandlerMsg26", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your registration request not approved. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg28() As String
            Get
                Return ResourceManager.GetString("HandlerMsg28", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile is not registered in the system, Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg29() As String
            Get
                Return ResourceManager.GetString("HandlerMsg29", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration successful.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg3() As String
            Get
                Return ResourceManager.GetString("HandlerMsg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle fuel limit for the day exceeded..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg30() As String
            Get
                Return ResourceManager.GetString("HandlerMsg30", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personal fuel limit for the day exceeded..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg31() As String
            Get
                Return ResourceManager.GetString("HandlerMsg31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hose does not exists..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg32() As String
            Get
                Return ResourceManager.GetString("HandlerMsg32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mobile is not registered in the system. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg33() As String
            Get
                Return ResourceManager.GetString("HandlerMsg33", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Pin. Please try again..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg34() As String
            Get
                Return ResourceManager.GetString("HandlerMsg34", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You have presented the wrong Fob/Card, please use another Fob/Card or Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg35() As String
            Get
                Return ResourceManager.GetString("HandlerMsg35", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Fob/Card detected, please enter vehicle number..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg36() As String
            Get
                Return ResourceManager.GetString("HandlerMsg36", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle number is already registered with another Fob/Card Number, please enter other vehicle number or Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg37() As String
            Get
                Return ResourceManager.GetString("HandlerMsg37", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Person is already registered with same Fob/Card Number, please enter other Fob/Card number or Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg38() As String
            Get
                Return ResourceManager.GetString("HandlerMsg38", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not registered, Error occurred while registering HUB..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg4() As String
            Get
                Return ResourceManager.GetString("HandlerMsg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Fob/Card detected, please enter person PIN..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg40() As String
            Get
                Return ResourceManager.GetString("HandlerMsg40", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Person PIN not found. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg41() As String
            Get
                Return ResourceManager.GetString("HandlerMsg41", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pin Number is already registered with another Fob/Card Number, please enter other Pin Number or Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg42() As String
            Get
                Return ResourceManager.GetString("HandlerMsg42", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fob/Card number is already registered with vehicle, please enter other Fob/Card Number or Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg43() As String
            Get
                Return ResourceManager.GetString("HandlerMsg43", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMEI_UDID not found. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg44() As String
            Get
                Return ResourceManager.GetString("HandlerMsg44", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vehicle not found, please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg45() As String
            Get
                Return ResourceManager.GetString("HandlerMsg45", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Fob/Card detected, please enter pin.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg46() As String
            Get
                Return ResourceManager.GetString("HandlerMsg46", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pin is already registered with another Fob/Card Number, please enter other vehicle number or Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg47() As String
            Get
                Return ResourceManager.GetString("HandlerMsg47", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fob/Card Number is assigned to Person..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg49() As String
            Get
                Return ResourceManager.GetString("HandlerMsg49", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMEI already exists..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg5() As String
            Get
                Return ResourceManager.GetString("HandlerMsg5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Some error occurred while processing the request. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg51() As String
            Get
                Return ResourceManager.GetString("HandlerMsg51", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentication failed, Invalid IMEI..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg52() As String
            Get
                Return ResourceManager.GetString("HandlerMsg52", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentication Failed, Please use the correct emailID which was supplied during registration..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg53() As String
            Get
                Return ResourceManager.GetString("HandlerMsg53", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentication successful.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg54() As String
            Get
                Return ResourceManager.GetString("HandlerMsg54", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authentication failed, you are not approved user..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg55() As String
            Get
                Return ResourceManager.GetString("HandlerMsg55", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Username or password, please try again..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg56() As String
            Get
                Return ResourceManager.GetString("HandlerMsg56", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fob/Card Number is assigned to Vehicle..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg57() As String
            Get
                Return ResourceManager.GetString("HandlerMsg57", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Company is inactive. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg58() As String
            Get
                Return ResourceManager.GetString("HandlerMsg58", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not registered, Other Phone numbers are registered to same email address..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg6() As String
            Get
                Return ResourceManager.GetString("HandlerMsg6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registration fail.
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg7() As String
            Get
                Return ResourceManager.GetString("HandlerMsg7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not registered, 21 phone numbers are already registered to same email address..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg8() As String
            Get
                Return ResourceManager.GetString("HandlerMsg8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account not exists. Please contact administrator..
        '''</summary>
        Public Shared ReadOnly Property HandlerMsg9() As String
            Get
                Return ResourceManager.GetString("HandlerMsg9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IMEI Number.
        '''</summary>
        Public Shared ReadOnly Property IMEINumber() As String
            Get
                Return ResourceManager.GetString("IMEINumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Public Shared ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Person Name.
        '''</summary>
        Public Shared ReadOnly Property PersonName() As String
            Get
                Return ResourceManager.GetString("PersonName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Personnel.
        '''</summary>
        Public Shared ReadOnly Property Personnel() As String
            Get
                Return ResourceManager.GetString("Personnel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pin Number.
        '''</summary>
        Public Shared ReadOnly Property PinNumber() As String
            Get
                Return ResourceManager.GetString("PinNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record saved..
        '''</summary>
        Public Shared ReadOnly Property RecordSaved() As String
            Get
                Return ResourceManager.GetString("RecordSaved", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record saving failed..
        '''</summary>
        Public Shared ReadOnly Property RecordSavingFailed() As String
            Get
                Return ResourceManager.GetString("RecordSavingFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset Password.
        '''</summary>
        Public Shared ReadOnly Property ResetPassword() As String
            Get
                Return ResourceManager.GetString("ResetPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roles.
        '''</summary>
        Public Shared ReadOnly Property Roles() As String
            Get
                Return ResourceManager.GetString("Roles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Public Shared ReadOnly Property Search() As String
            Get
                Return ResourceManager.GetString("Search", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to All records shown that match your criteria, click on Edit to see more fields.
        '''</summary>
        Public Shared ReadOnly Property SearchDesc() As String
            Get
                Return ResourceManager.GetString("SearchDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active.
        '''</summary>
        Public Shared ReadOnly Property this() As String
            Get
                Return ResourceManager.GetString("this", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to delete this User?.
        '''</summary>
        Public Shared ReadOnly Property UserDeleteMsg1() As String
            Get
                Return ResourceManager.GetString("UserDeleteMsg1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Records deleted Successfully..
        '''</summary>
        Public Shared ReadOnly Property UserDeleteMsg2() As String
            Get
                Return ResourceManager.GetString("UserDeleteMsg2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PERSONNEL is associated to a fueling Transaction(s), you must Delete Transaction(s) first to Delete this PERSONNEL..
        '''</summary>
        Public Shared ReadOnly Property UserDeleteMsg3() As String
            Get
                Return ResourceManager.GetString("UserDeleteMsg3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Records deletion failed..
        '''</summary>
        Public Shared ReadOnly Property UserDeleteMsg4() As String
            Get
                Return ResourceManager.GetString("UserDeleteMsg4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Public Shared ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
