'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Personnel
    
    '''<summary>
    '''up_Main control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up_Main As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblSiteMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSiteMessage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UP_Sites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP_Sites As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''gv_Sites control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_Sites As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnCancelSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelSite As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblFuelingTimes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFuelingTimes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UP_FuelingTimes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UP_FuelingTimes As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''gv_FuelingTimes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_FuelingTimes As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''btnCancelFuelingTimes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelFuelingTimes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnMyModalActiveInActiveNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMyModalActiveInActiveNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnMyModalActiveInActiveSuccess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMyModalActiveInActiveSuccess As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblMessageRedirectToVehicleMapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessageRedirectToVehicleMapping As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnRedirectToVehicleMappingNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirectToVehicleMappingNo As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnRedirectToVehicleMappingYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirectToVehicleMappingYes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''message control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents message As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ErrorMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ErrorMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CHK_HubUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_HubUser As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtPersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPersonName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''REV_PersonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REV_PersonName As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''LBL_PersonError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBL_PersonError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''HDF_PersonnelId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDF_PersonnelId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HDF_UniqueUserId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDF_UniqueUserId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HDF_TotalPersonnel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDF_TotalPersonnel As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''HDF_PreviousPreAuthCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDF_PreviousPreAuthCount As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txtPreAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPreAuth As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPreAuthNotUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreAuthNotUsed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblPreAuthUsed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPreAuthUsed As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CMV_PreAuth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CMV_PreAuth As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''AccessLevelsShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccessLevelsShow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''AccessLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AccessLevels As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DDL_AccessLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_AccessLevels As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblAccessLevels control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccessLevels As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ChangePWDLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangePWDLbl As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''ChangePWDCHK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChangePWDCHK As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CHK_ChangePWD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_ChangePWD As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtPinNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPinNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''REV_PinNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REV_PinNumber As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''txtFuelLimitPertxtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelLimitPertxtn As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CMV_FuelLimitPerTxtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CMV_FuelLimitPerTxtn As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RDFEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDFEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''txtFuelLimitPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFuelLimitPerDay As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CMV_FuelLimitPerDay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CMV_FuelLimitPerDay As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''PWDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PWDLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PWDTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PWDTextbox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtUserPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''LBLPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LBLPassword As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CPWDHide1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPWDHide1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''VehicleHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleHide As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''VehicleHide1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VehicleHide1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''btnAddVehicles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddVehicles As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''CPWDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPWDLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''CPWDTextbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPWDTextbox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConfirmPassword As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''CompareValidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompareValidator As Global.System.Web.UI.WebControls.CompareValidator
    
    '''<summary>
    '''RFDCResetPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RFDCResetPassword As Global.System.Web.UI.WebControls.RequiredFieldValidator
    
    '''<summary>
    '''CPWDHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CPWDHide As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TXT_FoBNUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_FoBNUM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtPhoneNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPhoneNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblPhoneError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPhoneError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''divIMEI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divIMEI As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtIMEINumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIMEINumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnIMEIPersonnelMapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnIMEIPersonnelMapping As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''divIMEIAdjustment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divIMEIAdjustment As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''UFLSLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UFLSLabel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''UFLSCheckbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UFLSCheckbox As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chkSoftUpdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSoftUpdate As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DDL_Department control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Department As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbldepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldepartment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkIsApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsApproved As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''DDL_DepartmentNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_DepartmentNumber As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''CHK_SendTransactionEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_SendTransactionEmail As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''txtExportCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExportCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''REV_ExportCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents REV_ExportCode As Global.System.Web.UI.WebControls.RegularExpressionValidator
    
    '''<summary>
    '''divAdditionalEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdditionalEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtAdditionalEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdditionalEmail As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''divCollectDiagnosticLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCollectDiagnosticLogs As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''chk_CollectDiagnosticLogs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_CollectDiagnosticLogs As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCompany As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DDL_Customer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_Customer As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblTearmsAndPolicyAccepted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTearmsAndPolicyAccepted As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblDateOfAcceptance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateOfAcceptance As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSaveAndAddNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAndAddNew As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnFirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFirst As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnprevious control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnprevious As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblof control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblof As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnLast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnLast As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hdfConfirmActiveInactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfConfirmActiveInactive As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdfDirtyFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfDirtyFlag As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''PWDHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PWDHide As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
